<a href="https://colab.research.google.com/github/preetamjumech/LoRA/blob/main/LoRA(Low_rank_Adaptation_of_large_language_models)_Pytorch_31_01_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SVD(Singluar Value Decomposition)

In [1]:
import torch
import numpy as np
_ = torch.manual_seed(0)

In [2]:
for _ in range(5):
    print(_)

0
1
2
3
4


In [4]:
torch.randn(2,4)

tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380]])

In [5]:
# Generate a rank-deficient matrix w
d, k = 10,10
w_rank = 2
w = torch.randn(d,w_rank) @ torch.randn(w_rank,k)
print(w)

tensor([[ 2.1643,  0.6744, -1.2905,  1.8246,  0.6706, -2.8475, -1.0359, -3.5343,
          0.4691, -0.6535],
        [-0.9974, -0.2896,  0.5678, -0.8275, -0.4137,  1.1944,  0.3716,  1.4960,
         -0.1449,  0.3268],
        [-0.2241, -0.1818,  0.2757, -0.2593,  0.4838,  0.9175,  0.6661,  1.0675,
         -0.4251, -0.0676],
        [-0.6295, -0.2886,  0.4927, -0.5888,  0.2616,  1.3423,  0.7626,  1.6071,
         -0.4473,  0.0784],
        [ 0.8609,  0.1478, -0.3605,  0.6502,  0.8616, -0.4631,  0.1888, -0.6515,
         -0.2182, -0.4055],
        [-0.4132, -0.2426,  0.3908, -0.4199,  0.4340,  1.1764,  0.7656,  1.3876,
         -0.4721, -0.0127],
        [-2.6355, -0.4010,  1.0383, -1.9579, -2.8924,  1.1311, -0.8353,  1.6714,
          0.8415,  1.3035],
        [ 2.0717,  0.7106, -1.3179,  1.7875,  0.3205, -3.0875, -1.3163, -3.7907,
          0.6678, -0.5470],
        [-0.3695, -0.4786,  0.6814, -0.5398,  1.6806,  2.5066,  1.9901,  2.8798,
         -1.3018, -0.3275],
        [ 0.2817,  

In [14]:
#Evaluate the rank of matrix w

w_r = np.linalg.matrix_rank(w)
print(w_r)

2


In [15]:
#dot Product
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a*b

array([[ 5, 12],
       [21, 32]])

In [16]:
#multiplication
a@b

array([[19, 22],
       [43, 50]])

In [23]:
u,s,v = torch.svd(w)
print(u)
print(s)
print(v)

tensor([[-0.4883, -0.1729,  0.8217,  0.1592, -0.0742, -0.1205,  0.0552,  0.0794,
         -0.0088,  0.0418],
        [ 0.2083,  0.1053,  0.0057,  0.6309, -0.1819,  0.1568, -0.4695,  0.4773,
         -0.1032,  0.1755],
        [ 0.1390, -0.1174,  0.1418,  0.1548, -0.0640,  0.2301, -0.2408, -0.2838,
         -0.0824, -0.8488],
        [ 0.2151, -0.0614,  0.0934,  0.2008,  0.1002,  0.5313,  0.7157,  0.2749,
          0.1234, -0.0745],
        [-0.0991, -0.2143, -0.0461, -0.0791, -0.1340,  0.2105, -0.2517,  0.0076,
          0.8992,  0.0400],
        [ 0.1831, -0.1045, -0.0304, -0.1534, -0.1577, -0.5900,  0.1461,  0.6002,
          0.1481, -0.3932],
        [ 0.2627,  0.7182,  0.3565, -0.3283, -0.3943,  0.1187, -0.0115, -0.0250,
          0.0996,  0.0072],
        [-0.5188, -0.0868, -0.3030, -0.2456, -0.5573,  0.3401,  0.0227,  0.2497,
         -0.2692, -0.0979],
        [ 0.3704, -0.4096,  0.0310,  0.1559, -0.6433, -0.1708,  0.1959, -0.3677,
         -0.0494,  0.2253],
        [-0.3659,  

In [22]:
# For rank-r factorization, keeping only the first r singular values
u_r = u[:,:w_r]
print(u_r)
s_r = torch.diag(s[:w_r])
print(s_r)
v_r = v[:,:w_r].T
print(v_r)

tensor([[-0.4883, -0.1729],
        [ 0.2083,  0.1053],
        [ 0.1390, -0.1174],
        [ 0.2151, -0.0614],
        [-0.0991, -0.2143],
        [ 0.1831, -0.1045],
        [ 0.2627,  0.7182],
        [-0.5188, -0.0868],
        [ 0.3704, -0.4096],
        [-0.3659,  0.4400]])
tensor([[11.5557,  0.0000],
        [ 0.0000,  5.9636]])
tensor([[-0.3115, -0.1176,  0.2118, -0.2755,  0.0052,  0.5243,  0.2518,  0.6376,
         -0.1367,  0.0692],
        [-0.3945, -0.0102,  0.0923, -0.2618, -0.6790, -0.1075, -0.3735, -0.0617,
          0.2934,  0.2553]])


In [24]:
B = u_r@s_r
A = v_r
print(B.shape)
print(A.shape)

torch.Size([10, 2])
torch.Size([2, 10])


In [25]:
bias = torch.randn(d)
bias

tensor([ 0.1318,  1.0198, -0.4468,  0.4520, -0.9759,  0.7112, -0.7582, -0.6436,
        -0.6462, -0.1591])

In [26]:
x = torch.randn(d)
x

tensor([-1.7787,  0.8477,  0.2459, -0.1312, -0.1785, -0.5959,  0.2739,  0.5679,
        -0.6731, -1.2095])

In [27]:
print(w.shape)
print(x.shape)
print(bias.shape)

torch.Size([10, 10])
torch.Size([10])
torch.Size([10])


In [28]:
y = w@x + bias
print(y.shape)
print(y)

torch.Size([10])
tensor([-3.9420,  2.8123,  0.4229,  2.0068, -2.1147,  1.9442,  2.5216, -4.8034,
         1.5030, -2.2204])


In [29]:
y_prime = (B@A)@x + bias
print(y_prime.shape)
print(y_prime)

torch.Size([10])
tensor([-3.9420,  2.8123,  0.4229,  2.0068, -2.1147,  1.9442,  2.5216, -4.8034,
         1.5030, -2.2204])


In [31]:
#no of parameters
print(type(w))
print(w.nelement())
print(B.nelement() + A.nelement())

<class 'torch.Tensor'>
100
40


# LoRA implementation using PyTorch

In [4]:
import torch
import torchvision.datasets as datasets
import torchvision.transforms as transforms
import torch.nn as nn
from tqdm import tqdm

In [3]:
_ = torch.manual_seed(0)

In [12]:
transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.1307,),(0.3081,))])
mnist_trainset = datasets.MNIST(root = './data',train = True, download = True, transform = transform)
train_loader = torch.utils.data.DataLoader(mnist_trainset, batch_size = 10, shuffle = True)

mnist_testset = datasets.MNIST(root = './data',train = False, download = True, transform = transform)
test_loader = torch.utils.data.DataLoader(mnist_testset, batch_size = 10, shuffle = True)

In [7]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [8]:
class NormalNet(nn.Module):
  def __init__(self,hidden_size_1 = 1000, hidden_size_2 = 2000):
    super(NormalNet,self).__init__()
    self.linear1 = nn.Linear(28*28,hidden_size_1)
    self.linear2 = nn.Linear(hidden_size_1,hidden_size_2)
    self.linear3 = nn.Linear(hidden_size_2,10)
    self.relu = nn.ReLU()

  def forward(self, img):
    x = img.view(-1,28*28)
    x = self.relu(self.linear1(x))
    x = self.relu(self.linear2(x))
    x = self.linear3(x)
    return x

net = NormalNet().to(device)

In [9]:
def train(train_loader, net, epochs=5, total_iterations_limit=None):
    cross_el = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(net.parameters(), lr=0.001)

    total_iterations = 0

    for epoch in range(epochs):
        net.train()

        loss_sum = 0
        num_iterations = 0

        data_iterator = tqdm(train_loader, desc=f'Epoch {epoch+1}')
        if total_iterations_limit is not None:
            data_iterator.total = total_iterations_limit
        for data in data_iterator:
            num_iterations += 1
            total_iterations += 1
            x, y = data
            x = x.to(device)
            y = y.to(device)
            optimizer.zero_grad()
            output = net(x.view(-1, 28*28))
            loss = cross_el(output, y)
            loss_sum += loss.item()
            avg_loss = loss_sum / num_iterations
            data_iterator.set_postfix(loss=avg_loss)
            loss.backward()
            optimizer.step()

            if total_iterations_limit is not None and total_iterations >= total_iterations_limit:
                return

train(train_loader, net, epochs=1)

Epoch 1: 100%|██████████| 6000/6000 [08:34<00:00, 11.67it/s, loss=0.236]


In [10]:
#Keeping a copy of the original weights (cloning them) so later we can prove that a fine-tuning with LoRA doesn't alter the original weights
original_weights = {}
for name, param in net.named_parameters():
    original_weights[name] = param.clone().detach()

In [15]:
len(original_weights)

6

In [13]:
def test():
    correct = 0
    total = 0

    wrong_counts = [0 for i in range(10)]

    with torch.no_grad():
        for data in tqdm(test_loader, desc='Testing'):
            x, y = data
            x = x.to(device)
            y = y.to(device)
            output = net(x.view(-1, 784))
            for idx, i in enumerate(output):
                if torch.argmax(i) == y[idx]:
                    correct +=1
                else:
                    wrong_counts[y[idx]] +=1
                total +=1
    print(f'Accuracy: {round(correct/total, 3)}')
    for i in range(len(wrong_counts)):
        print(f'wrong counts for the digit {i}: {wrong_counts[i]}')

test()

Testing: 100%|██████████| 1000/1000 [00:07<00:00, 136.16it/s]

Accuracy: 0.954
wrong counts for the digit 0: 31
wrong counts for the digit 1: 17
wrong counts for the digit 2: 46
wrong counts for the digit 3: 74
wrong counts for the digit 4: 29
wrong counts for the digit 5: 7
wrong counts for the digit 6: 36
wrong counts for the digit 7: 80
wrong counts for the digit 8: 25
wrong counts for the digit 9: 116


In [16]:
# Print the size of the weights matrices of the network
# Save the count of the total number of parameters
total_parameters_original = 0
for index, layer in enumerate([net.linear1, net.linear2, net.linear3]):
    total_parameters_original += layer.weight.nelement() + layer.bias.nelement()
    print(f'Layer {index+1}: W: {layer.weight.shape} + B: {layer.bias.shape}')
print(f'Total number of parameters: {total_parameters_original:,}')

Layer 1: W: torch.Size([1000, 784]) + B: torch.Size([1000])
Layer 2: W: torch.Size([2000, 1000]) + B: torch.Size([2000])
Layer 3: W: torch.Size([10, 2000]) + B: torch.Size([10])
Total number of parameters: 2,807,010


In [17]:
class LoRAParametrization(nn.Module):
    def __init__(self, features_in, features_out, rank=1, alpha=1, device='cpu'):
        super().__init__()
        # Section 4.1 of the paper:
        #   We use a random Gaussian initialization for A and zero for B, so ∆W = BA is zero at the beginning of training
        self.lora_A = nn.Parameter(torch.zeros((rank,features_out)).to(device))
        self.lora_B = nn.Parameter(torch.zeros((features_in, rank)).to(device))
        nn.init.normal_(self.lora_A, mean=0, std=1)

        # Section 4.1 of the paper:
        #   We then scale ∆Wx by α/r , where α is a constant in r.
        #   When optimizing with Adam, tuning α is roughly the same as tuning the learning rate if we scale the initialization appropriately.
        #   As a result, we simply set α to the first r we try and do not tune it.
        #   This scaling helps to reduce the need to retune hyperparameters when we vary r.
        self.scale = alpha / rank
        self.enabled = True

    def forward(self, original_weights):
        if self.enabled:
            # Return W + (B*A)*scale
            return original_weights + torch.matmul(self.lora_B, self.lora_A).view(original_weights.shape) * self.scale
        else:
            return original_weights

In [18]:
import torch.nn.utils.parametrize as parametrize

def linear_layer_parameterization(layer, device, rank=1, lora_alpha=1):
    # Only add the parameterization to the weight matrix, ignore the Bias

    # From section 4.2 of the paper:
    #   We limit our study to only adapting the attention weights for downstream tasks and freeze the MLP modules (so they are not trained in downstream tasks) both for simplicity and parameter-efficiency.
    #   [...]
    #   We leave the empirical investigation of [...], and biases to a future work.

    features_in, features_out = layer.weight.shape
    return LoRAParametrization(
        features_in, features_out, rank=rank, alpha=lora_alpha, device=device
    )

parametrize.register_parametrization(
    net.linear1, "weight", linear_layer_parameterization(net.linear1, device)
)
parametrize.register_parametrization(
    net.linear2, "weight", linear_layer_parameterization(net.linear2, device)
)
parametrize.register_parametrization(
    net.linear3, "weight", linear_layer_parameterization(net.linear3, device)
)


def enable_disable_lora(enabled=True):
    for layer in [net.linear1, net.linear2, net.linear3]:
        layer.parametrizations["weight"][0].enabled = enabled

In [19]:
total_parameters_lora = 0
total_parameters_non_lora = 0
for index, layer in enumerate([net.linear1, net.linear2, net.linear3]):
    total_parameters_lora += layer.parametrizations["weight"][0].lora_A.nelement() + layer.parametrizations["weight"][0].lora_B.nelement()
    total_parameters_non_lora += layer.weight.nelement() + layer.bias.nelement()
    print(
        f'Layer {index+1}: W: {layer.weight.shape} + B: {layer.bias.shape} + Lora_A: {layer.parametrizations["weight"][0].lora_A.shape} + Lora_B: {layer.parametrizations["weight"][0].lora_B.shape}'
    )
# The non-LoRA parameters count must match the original network
assert total_parameters_non_lora == total_parameters_original
print(f'Total number of parameters (original): {total_parameters_non_lora:,}')
print(f'Total number of parameters (original + LoRA): {total_parameters_lora + total_parameters_non_lora:,}')
print(f'Parameters introduced by LoRA: {total_parameters_lora:,}')
parameters_incremment = (total_parameters_lora / total_parameters_non_lora) * 100
print(f'Parameters incremment: {parameters_incremment:.3f}%')

Layer 1: W: torch.Size([1000, 784]) + B: torch.Size([1000]) + Lora_A: torch.Size([1, 784]) + Lora_B: torch.Size([1000, 1])
Layer 2: W: torch.Size([2000, 1000]) + B: torch.Size([2000]) + Lora_A: torch.Size([1, 1000]) + Lora_B: torch.Size([2000, 1])
Layer 3: W: torch.Size([10, 2000]) + B: torch.Size([10]) + Lora_A: torch.Size([1, 2000]) + Lora_B: torch.Size([10, 1])
Total number of parameters (original): 2,807,010
Total number of parameters (original + LoRA): 2,813,804
Parameters introduced by LoRA: 6,794
Parameters incremment: 0.242%


In [20]:
# Freeze the non-Lora parameters
for name, param in net.named_parameters():
    if 'lora' not in name:
        print(f'Freezing non-LoRA parameter {name}')
        param.requires_grad = False

# Load the MNIST dataset again, by keeping only the digit 9
mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
exclude_indices = mnist_trainset.targets == 9
mnist_trainset.data = mnist_trainset.data[exclude_indices]
mnist_trainset.targets = mnist_trainset.targets[exclude_indices]
# Create a dataloader for the training
train_loader = torch.utils.data.DataLoader(mnist_trainset, batch_size=10, shuffle=True)

# Train the network with LoRA only on the digit 9 and only for 100 batches (hoping that it would improve the performance on the digit 9)
train(train_loader, net, epochs=1, total_iterations_limit=100)

Freezing non-LoRA parameter linear1.bias
Freezing non-LoRA parameter linear1.parametrizations.weight.original
Freezing non-LoRA parameter linear2.bias
Freezing non-LoRA parameter linear2.parametrizations.weight.original
Freezing non-LoRA parameter linear3.bias
Freezing non-LoRA parameter linear3.parametrizations.weight.original


Epoch 1:  99%|█████████▉| 99/100 [00:03<00:00, 31.77it/s, loss=0.115]


In [21]:
# Check that the frozen parameters are still unchanged by the finetuning
assert torch.all(net.linear1.parametrizations.weight.original == original_weights['linear1.weight'])
assert torch.all(net.linear2.parametrizations.weight.original == original_weights['linear2.weight'])
assert torch.all(net.linear3.parametrizations.weight.original == original_weights['linear3.weight'])

enable_disable_lora(enabled=True)
# The new linear1.weight is obtained by the "forward" function of our LoRA parametrization
# The original weights have been moved to net.linear1.parametrizations.weight.original
# More info here: https://pytorch.org/tutorials/intermediate/parametrizations.html#inspecting-a-parametrized-module
assert torch.equal(net.linear1.weight, net.linear1.parametrizations.weight.original + (net.linear1.parametrizations.weight[0].lora_B @ net.linear1.parametrizations.weight[0].lora_A) * net.linear1.parametrizations.weight[0].scale)

enable_disable_lora(enabled=False)
# If we disable LoRA, the linear1.weight is the original one
assert torch.equal(net.linear1.weight, original_weights['linear1.weight'])

In [22]:
# Test with LoRA enabled
enable_disable_lora(enabled=True)
test()

Testing: 100%|██████████| 1000/1000 [00:16<00:00, 62.19it/s]

Accuracy: 0.876
wrong counts for the digit 0: 130
wrong counts for the digit 1: 28
wrong counts for the digit 2: 122
wrong counts for the digit 3: 262
wrong counts for the digit 4: 179
wrong counts for the digit 5: 59
wrong counts for the digit 6: 40
wrong counts for the digit 7: 214
wrong counts for the digit 8: 200
wrong counts for the digit 9: 4


In [23]:
# Test with LoRA disabled
enable_disable_lora(enabled=False)
test()

Testing: 100%|██████████| 1000/1000 [00:08<00:00, 116.68it/s]

Accuracy: 0.954
wrong counts for the digit 0: 31
wrong counts for the digit 1: 17
wrong counts for the digit 2: 46
wrong counts for the digit 3: 74
wrong counts for the digit 4: 29
wrong counts for the digit 5: 7
wrong counts for the digit 6: 36
wrong counts for the digit 7: 80
wrong counts for the digit 8: 25
wrong counts for the digit 9: 116
